import type { Student } from "../_lib/types";

export const students: Student[] = [
  {
    id: 1,
    name: "Алекс Томпсон",
    email: "alex@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "online",
    currentQuestion: 23,
    totalQuestions: 50,
    tabSwitches: 0,
  },
  {
    id: 2,
    name: "Жордан Мартинез",
    email: "j.martinez@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "online",
    currentQuestion: 31,
    totalQuestions: 50,
    tabSwitches: 0,
  },
  {
    id: 3,
    name: "Сэм Вилсон",
    email: "s.wilson@university.edu",
    className: "МТ102 - Өгөгдлийн бүтэц",
    status: "online",
    currentQuestion: 18,
    totalQuestions: 50,
    tabSwitches: 0,
  },
  {
    id: 4,
    name: "Кейси Браун",
    email: "c.brown@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "offline",
    currentQuestion: 12,
    totalQuestions: 50,
    tabSwitches: 5,
  },
  {
    id: 5,
    name: "Морган Дэвис",
    email: "m.davis@university.edu",
    className: "МТ201 - Алгоритм",
    status: "submitted",
    currentQuestion: 50,
    totalQuestions: 50,
    submittedMinutesAgo: 18,
    tabSwitches: 0,
  },
  {
    id: 6,
    name: "Райли Жонсон",
    email: "r.johnson@university.edu",
    className: "МТ102 - Өгөгдлийн бүтэц",
    status: "online",
    currentQuestion: 42,
    totalQuestions: 50,
    tabSwitches: 0,
  },
  {
    id: 7,
    name: "Тэйлор Ли",
    email: "t.lee@university.edu",
    className: "МТ201 - Алгоритм",
    status: "online",
    currentQuestion: 15,
    totalQuestions: 50,
    tabSwitches: 3,
  },
  {
    id: 8,
    name: "Жэйми Чен",
    email: "j.chen@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "submitted",
    currentQuestion: 50,
    totalQuestions: 50,
    submittedMinutesAgo: 28,
    tabSwitches: 0,
  },
];
