export const EXAMS_DATA = [
  {
    id: 1,
    title: "Явцын шалгалт",
    course: "CS 101 - Компьютерийн ШУ",
    date: "Mar 25, 2026",
    time: "10:00 AM",
    students: 45,
    duration: "2 цаг",
    status: "Авагдаж байгаа",
    submissions: 12,
  },
  {
    id: 2,
    title: "Шалгалт 3: Эрэмбэлэх алгоритм",
    course: "CS 201 - Өгөгдлийн бүтэц алгоритм",
    date: "Mar 28, 2026",
    time: "2:00 PM",
    students: 38,
    duration: "1 цаг",
    status: "Төлөвлөгдсөн",
  },
  {
    id: 3,
    title: "Эцсийн шалгалт",
    course: "CS 301 - Өгөгдлийн сангийн бүтэц",
    date: "Apr 2, 2026",
    time: "9:00 AM",
    students: 52,
    duration: "3 цаг",
    status: "Төлөвлөгдсөн",
  },
  {
    id: 4,
    title: "Шалгалт 2: SQL нэмэх",
    course: "CS 301 - Өгөгдлийн сангийн бүтэц",
    date: "Mar 20, 2026",
    time: "11:00 AM",
    students: 52,
    duration: "45 минут",
    status: "Дууссан",
    averageScore: 78,
  },
  {
    id: 5,
    title: "Явцын шалгалт",
    course: "CS 201 - Өгөгдлийн бүтэц алгоритм",
    date: "Mar 15, 2026",
    time: "2:00 PM",
    students: 38,
    duration: "2 цаг",
    status: "Дууссан",
    averageScore: 82,
  },
  {
    id: 6,
    title: "Бэлтгэл шалгалт",
    course: "CS 401 - Софтвейр Инженер",
    date: "TBD",
    time: "TBD",
    students: 31,
    duration: "1 цаг",
    status: "Драфт",
  },
];
